---
- name: Play with two tasks, one uses privilege escalation
  hosts: nodes
  become: false
  gather_facts: false
  tasks:
  - name: This task needs privileges
    file:
      path: /root/file.txt
      state: touch
      mode: 0644
    become: true

  - name: This task does not need privileges
    file:
      path: /home/ansible/file.txt
      state: touch
      mode: 0644
    become: false
